proxy-groups:
  - {name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©, type: select, include-all-providers: true, proxies: [DIRECT]}
  - {name: ğŸƒ YOUTUBE, type: select, include-all-providers: true, proxies: [ğŸš€ èŠ‚ç‚¹é€‰æ‹©]}
  - {name: ğŸŒˆ NETFLIX, type: select, include-all-providers: true, proxies: [ğŸš€ èŠ‚ç‚¹é€‰æ‹©]}
  - {name: ğŸª DisneyPlus, type: select, include-all-providers: true, proxies: [ğŸš€ èŠ‚ç‚¹é€‰æ‹©]}
  - {name: ğŸ”¶ å›½é™…äºšé©¬é€Š, type: select, include-all-providers: true, proxies: [ğŸš€ èŠ‚ç‚¹é€‰æ‹©]}
  - {name: ğŸ‘‘ HBO, type: select, include-all-providers: true, proxies: [ğŸš€ èŠ‚ç‚¹é€‰æ‹©]}
  - {name: ğŸ¬ OneDrive, type: select, include-all-providers: true, proxies: [ğŸš€ èŠ‚ç‚¹é€‰æ‹©]}
  - {name: ğŸ‘¨ğŸ¿â€ğŸ’» GitHub, type: select, include-all-providers: true, proxies: [ğŸš€ èŠ‚ç‚¹é€‰æ‹©]}
  - {name: ğŸ¤– ChatGPT, type: select, include-all-providers: true, proxies: [ğŸš€ èŠ‚ç‚¹é€‰æ‹©]}
  - {name: ğŸ’§ Copilot, type: select, include-all-providers: true, proxies: [ğŸš€ èŠ‚ç‚¹é€‰æ‹©]}
  - {name: ğŸ“² ç”µæŠ¥æ¶ˆæ¯, type: select, include-all-providers: true, proxies: [ğŸš€ èŠ‚ç‚¹é€‰æ‹©]}
  - {name: ğŸŸ ç¾å›½, type: select, include-all-providers: true, proxies: [ğŸš€ èŠ‚ç‚¹é€‰æ‹©]}
  - {name: ğŸ AppleTV, type: select, include-all-providers: true, proxies: [ğŸš€ èŠ‚ç‚¹é€‰æ‹©]}
  - {name: ğŸ“ WIFICALL, type: select, include-all-providers: true, proxies: [ğŸš€ èŠ‚ç‚¹é€‰æ‹©]}
  - {name: ğŸ’³ Paypal, type: select, include-all-providers: true, proxies: [ğŸš€ èŠ‚ç‚¹é€‰æ‹©]}
  - {name: ğŸ›ï¸ eBay, type: select, include-all-providers: true, proxies: [ğŸš€ èŠ‚ç‚¹é€‰æ‹©]}
  - {name: ğŸ§ spotify, type: select, include-all-providers: true, proxies: [ğŸš€ èŠ‚ç‚¹é€‰æ‹©]}
  - {name: ğŸµ TikTok, type: select, include-all-providers: true, proxies: [ğŸš€ èŠ‚ç‚¹é€‰æ‹©]}
  - {name: ğŸ® æ¸¸æˆå›½é™…, type: select, include-all-providers: true, proxies: [ğŸš€ èŠ‚ç‚¹é€‰æ‹©]}
  - {name: ğŸ è‹¹æœæœåŠ¡, type: select, include-all-providers: true, proxies: [DIRECT, ğŸš€ èŠ‚ç‚¹é€‰æ‹©]}
  - {name: ğŸªŸ Microsoft, type: select, include-all-providers: true, proxies: [DIRECT, ğŸš€ èŠ‚ç‚¹é€‰æ‹©]}
  - {name: ğŸ”¶ ä¸­å›½äºšé©¬é€Š, type: select, include-all-providers: true, proxies: [DIRECT, ğŸš€ èŠ‚ç‚¹é€‰æ‹©]}
  - {name: ğŸ“º çˆ±å¥‡è‰º, type: select, include-all-providers: true, proxies: [DIRECT, ğŸš€ èŠ‚ç‚¹é€‰æ‹©]}
  - {name: ğŸ“º å“”å“©å“”å“©, type: select, include-all-providers: true, proxies: [DIRECT, ğŸš€ èŠ‚ç‚¹é€‰æ‹©]}
  - {name: â¤ï¸ Embyå…¬ç›Šæœ, type: select, include-all-providers: true, proxies: [DIRECT, ğŸš€ èŠ‚ç‚¹é€‰æ‹©]}
  - {name: ğŸ® æ¸¸æˆä¸­å›½, type: select, include-all-providers: true, proxies: [DIRECT, ğŸš€ èŠ‚ç‚¹é€‰æ‹©]}
  - {name: ğŸ¯ å…¨çƒç›´è¿, type: select, include-all-providers: true, proxies: [DIRECT, ğŸš€ èŠ‚ç‚¹é€‰æ‹©]}
  - {name: ğŸ›‘ å¹¿å‘Šæ‹¦æˆª, type: select, include-all-providers: true, proxies: [REJECT, DIRECT]}
  - {name: ğŸƒ åº”ç”¨å‡€åŒ–, type: select, include-all-providers: true, proxies: [REJECT, DIRECT]}
  - {name: ğŸŸ æ¼ç½‘ä¹‹é±¼, type: select, include-all-providers: true, proxies: [ğŸš€ èŠ‚ç‚¹é€‰æ‹©]}
  - {name: ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹, type: select, include-all-providers: true, proxies: [{providers_tags}], filter: "(?i)æ¸¯|hk|hongkong|hong kong"}
  - {name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, type: select, include-all-providers: true, proxies: [{providers_tags}], filter: "(?i)æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|JP|Japan"}
  - {name: ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹, type: select, include-all-providers: true, proxies: [{providers_tags}], filter: "(?i)ç¾|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|US|United States"}
  - {name: ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹, type: select, include-all-providers: true, proxies: [{providers_tags}], filter: "(?i)æ–°åŠ å¡|å¡|ç‹®åŸ|SG|Singapore"}
  - {name: ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹, type: select, include-all-providers: true, proxies: [{providers_tags}], filter: "(?i)KR|Korea|KOR|é¦–å°”|éŸ©|éŸ“"}
#  - {name: ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹`url-test`(æ¸¯|HK|hk|Hong Kong|HongKong|hongkong)`http://www.gstatic.com/generate_204`300,,50
#  - {name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹`url-test`(æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|JP|Japan)`http://www.gstatic.com/generate_204`300,,50
#  - {name: ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹`url-test`(ç¾|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|US|United States)`http://www.gstatic.com/generate_204`300,,150
#  - {name: ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹`url-test`(æ–°åŠ å¡|å¡|ç‹®åŸ|SG|Singapore)`http://www.gstatic.com/generate_204`300,,50
#  - {name: ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹`url-test`(KR|Korea|KOR|é¦–å°”|éŸ©|éŸ“)`http://www.gstatic.com/generate_204`300,,
#  - {name: ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹`url-test`(å°|æ–°åŒ—|å½°åŒ–|TW|Taiwan)`http://www.gstatic.com/generate_204`300,,50
#  - {name: ğŸ¥ å¥ˆé£èŠ‚ç‚¹`type: select`(NF|å¥ˆé£|è§£é”|Netflix|NETFLIX|Media)

rule-providers:
  YouTube:
    type: http
    behavior: classical
    url: "https://gh.sswiwi.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.yaml"
    path: ./providers/YouTube.yaml
    interval: 86400
  Netflix:
    type: http
    behavior: classical
    url: "https://gh.sswiwi.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix.yaml"
    path: ./providers/Netflix.yaml
    interval: 86400
  Disney:
    type: http
    behavior: classical
    url: "https://gh.sswiwi.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Disney/Disney.yaml"
    path: ./providers/Disney.yaml
    interval: 86400
  Amazon:
    type: http
    behavior: classical
    url: "https://gh.sswiwi.com/https://raw.githubusercontent.com/lusalem/ruleset/main/rules/clash/Amazon.yaml"
    path: ./providers/Amazon.yaml
    interval: 86400
  AmazonPrimeVideo:
    type: http
    behavior: classical
    url: "https://gh.sswiwi.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/AmazonPrimeVideo/AmazonPrimeVideo.yaml"
    path: ./providers/AmazonPrimeVideo.yaml
    interval: 86400
  HBO:
    type: http
    behavior: classical
    url: "https://gh.sswiwi.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/HBO/HBO.yaml"
    path: ./providers/HBO.yaml
    interval: 86400
  OneDrive:
    type: http
    behavior: classical
    url: "https://gh.sswiwi.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/OneDrive/OneDrive.yaml"
    path: ./providers/OneDrive.yaml
    interval: 86400
  GitHub:
    type: http
    behavior: classical
    url: "https://gh.sswiwi.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/GitHub/GitHub.yaml"
    path: ./providers/GitHub.yaml
    interval: 86400
  OpenAI:
    type: http
    behavior: classical
    url: "https://gh.sswiwi.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/OpenAI/OpenAI.yaml"
    path: ./providers/OpenAI.yaml
    interval: 86400
  Gemini:
    type: http
    behavior: classical
    url: "https://gh.sswiwi.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Gemini/Gemini.yaml"
    path: ./providers/Gemini.yaml
    interval: 86400
  Claude:
    type: http
    behavior: classical
    url: "https://gh.sswiwi.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Claude/Claude.yaml"
    path: ./providers/Claude.yaml
    interval: 86400
  ai_ip:
    type: http
    behavior: ipcidr
    url: "https://gh.sswiwi.com/https://raw.githubusercontent.com/lusalem/ruleset/main/rules/clash/ai_ip.yaml"
    path: ./providers/ai_ip.yaml
    interval: 86400
  Copilot:
    type: http
    behavior: classical
    url: "https://gh.sswiwi.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Copilot/Copilot.yaml"
    path: ./providers/Copilot.yaml
    interval: 86400
  Telegram:
    type: http
    behavior: classical
    url: "https://gh.sswiwi.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Telegram/Telegram.yaml"
    path: ./providers/Telegram.yaml
    interval: 86400
  us:
    type: http
    behavior: classical
    url: "https://gh.sswiwi.com/https://raw.githubusercontent.com/lusalem/ruleset/main/rules/clash/us.yaml"
    path: ./providers/us.yaml
    interval: 86400
  AppleTV:
    type: http
    behavior: classical
    url: "https://gh.sswiwi.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/AppleTV/AppleTV.yaml"
    path: ./providers/AppleTV.yaml
    interval: 86400
  wificall:
    type: http
    behavior: classical
    url: "https://gh.sswiwi.com/https://raw.githubusercontent.com/lusalem/ruleset/main/rules/clash/wificall.yaml"
    path: ./providers/wificall.yaml
    interval: 86400
  PayPal:
    type: http
    behavior: classical
    url: "https://gh.sswiwi.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/PayPal/PayPal.yaml"
    path: ./providers/PayPal.yaml
    interval: 86400
  ebay:
    type: http
    behavior: classical
    url: "https://gh.sswiwi.com/https://raw.githubusercontent.com/lusalem/ruleset/main/rules/clash/ebay.yaml"
    path: ./providers/ebay.yaml
    interval: 86400
  Spotify:
    type: http
    behavior: classical
    url: "https://gh.sswiwi.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Spotify/Spotify.yaml"
    path: ./providers/Spotify.yaml
    interval: 86400
  TikTok:
    type: http
    behavior: classical
    url: "https://gh.sswiwi.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/TikTok/TikTok.yaml"
    path: ./providers/TikTok.yaml
    interval: 86400
  Epic:
    type: http
    behavior: classical
    url: "https://gh.sswiwi.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Epic/Epic.yaml"
    path: ./providers/Epic.yaml
    interval: 86400
  Origin:
    type: http
    behavior: classical
    url: "https://gh.sswiwi.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Origin/Origin.yaml"
    path: ./providers/Origin.yaml
    interval: 86400
  Sony:
    type: http
    behavior: classical
    url: "https://gh.sswiwi.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Sony/Sony.yaml"
    path: ./providers/Sony.yaml
    interval: 86400
  Steam:
    type: http
    behavior: classical
    url: "https://gh.sswiwi.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Steam/Steam.yaml"
    path: ./providers/Steam.yaml
    interval: 86400
  Nintendo:
    type: http
    behavior: classical
    url: "https://gh.sswiwi.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Nintendo/Nintendo.yaml"
    path: ./providers/Nintendo.yaml
    interval: 86400
  GameDownload:
    type: http
    behavior: classical
    url: "https://gh.sswiwi.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/GameDownload/GameDownload.yaml"
    path: ./providers/GameDownload.yaml
    interval: 86400
  apple@cn:
    type: http
    behavior: classical
    url: "https://gh.sswiwi.com/https://raw.githubusercontent.com/lusalem/ruleset/main/rules/clash/apple@cn.yaml"
    path: ./providers/apple@cn.yaml
    interval: 86400
  microsoft@cn:
    type: http
    behavior: classical
    url: "https://gh.sswiwi.com/https://raw.githubusercontent.com/lusalem/ruleset/main/rules/clash/microsoft@cn.yaml"
    path: ./providers/microsoft@cn.yaml
    interval: 86400
  AmazonCN:
    type: http
    behavior: classical
    url: "https://gh.sswiwi.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/AmazonCN/AmazonCN.yaml"
    path: ./providers/AmazonCN.yaml
    interval: 86400
  iQIYI:
    type: http
    behavior: classical
    url: "https://gh.sswiwi.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/iQIYI/iQIYI.yaml"
    path: ./providers/iQIYI.yaml
    interval: 86400
  BiliBili:
    type: http
    behavior: classical
    url: "https://gh.sswiwi.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/BiliBili/BiliBili.yaml"
    path: ./providers/BiliBili.yaml
    interval: 86400
  emby:
    type: http
    behavior: classical
    url: "https://gh.sswiwi.com/https://raw.githubusercontent.com/lusalem/ruleset/main/rules/clash/emby.yaml"
    path: ./providers/emby.yaml
    interval: 86400
  GameDownloadCN:
    type: http
    behavior: classical
    url: "https://gh.sswiwi.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/GameDownloadCN/GameDownloadCN.yaml"
    path: ./providers/GameDownloadCN.yaml
    interval: 86400
  LocalAreaNetwork:
    type: http
    behavior: classical
    url: "https://gh.sswiwi.com/https://raw.githubusercontent.com/lusalem/ruleset/main/rules/clash/LocalAreaNetwork.yaml"
    path: ./providers/LocalAreaNetwork.yaml
    interval: 86400
  UnBan:
    type: http
    behavior: classical
    url: "https://gh.sswiwi.com/https://raw.githubusercontent.com/lusalem/ruleset/main/rules/clash/UnBan.yaml"
    path: ./providers/UnBan.yaml
    interval: 86400
  SteamCN:
    type: http
    behavior: classical
    url: "https://gh.sswiwi.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/SteamCN/SteamCN.yaml"
    path: ./providers/SteamCNv.yaml
    interval: 86400
  Proxy_Classical:
    type: http
    behavior: classical
    url: "https://gh.sswiwi.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Proxy/Proxy_Classical.yaml"
    path: ./providers/Proxy_Classical.yaml
    interval: 86400
  China_Classical:
    type: http
    behavior: classical
    url: "https://gh.sswiwi.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/China/China_Classical.yaml"
    path: ./providers/China_Classical.yaml
    interval: 86400
  ChinaIPs_Classical:
    type: http
    behavior: classical
    url: "https://gh.sswiwi.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/ChinaIPs/ChinaIPs_Classical.yaml"
    path: ./providers/ChinaIPs_Classical.yaml
    interval: 86400
  Download:
    type: http
    behavior: classical
    url: "https://gh.sswiwi.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Download/Download.yaml"
    path: ./providers/Download.yaml
    interval: 86400
  BanAD:
    type: http
    behavior: classical
    url: "https://gh.sswiwi.com/https://raw.githubusercontent.com/lusalem/ruleset/main/rules/clash/BanAD.yaml"
    path: ./providers/BanAD.yaml
    interval: 86400
  BanProgramAD:
    type: http
    behavior: classical
    url: "https://gh.sswiwi.com/https://raw.githubusercontent.com/lusalem/ruleset/main/rules/clash/BanProgramAD.yaml"
    path: ./providers/BanProgramAD.yaml
    interval: 86400

rules:
  - RULE-SET,YouTube,ğŸƒ YOUTUBE
  - RULE-SET,Netflix,ğŸŒˆ NETFLIX
  - RULE-SET,Disney,ğŸª DisneyPlus
  - RULE-SET,Amazon,ğŸ”¶ å›½é™…äºšé©¬é€Š
  - RULE-SET,AmazonPrimeVideo,ğŸ”¶ å›½é™…äºšé©¬é€Š
  - RULE-SET,HBO,ğŸ‘‘ HBO
  - RULE-SET,OneDrive,ğŸ¬ OneDrive
  - RULE-SET,GitHub,ğŸ‘¨ğŸ¿â€ğŸ’» GitHub
  - RULE-SET,OpenAI,ğŸ¤– ChatGPT
  - RULE-SET,Gemini,ğŸ¤– ChatGPT
  - RULE-SET,Claude,ğŸ¤– ChatGPT
  - RULE-SET,ai_ip,ğŸ¤– ChatGPT
  - RULE-SET,Copilot,ğŸ’§ Copilot
  - RULE-SET,Telegram,ğŸ“² ç”µæŠ¥æ¶ˆæ¯
  - RULE-SET,us,ğŸŸ ç¾å›½
  - RULE-SET,AppleTV,ğŸ AppleTV
  - RULE-SET,wificall,ğŸ“ WIFICALL
  - RULE-SET,PayPal,ğŸ’³ Paypal
  - RULE-SET,ebay,ğŸ›ï¸ eBay
  - RULE-SET,Spotify,ğŸ§ spotify
  - RULE-SET,TikTok,ğŸµ TikTok
  - RULE-SET,Epic,ğŸ® æ¸¸æˆå›½é™…
  - RULE-SET,Origin,ğŸ® æ¸¸æˆå›½é™…
  - RULE-SET,Sony,ğŸ® æ¸¸æˆå›½é™…
  - RULE-SET,Steam,ğŸ® æ¸¸æˆå›½é™…
  - RULE-SET,Nintendo,ğŸ® æ¸¸æˆå›½é™…
  - RULE-SET,GameDownload,ğŸ® æ¸¸æˆå›½é™…
  - RULE-SET,apple@cn,ğŸ è‹¹æœæœåŠ¡
  - RULE-SET,microsoft@cn,ğŸªŸ Microsoft
  - RULE-SET,AmazonCN,ğŸ”¶ ä¸­å›½äºšé©¬é€Š
  - RULE-SET,iQIYI,ğŸ“º çˆ±å¥‡è‰º
  - RULE-SET,BiliBili,ğŸ“º å“”å“©å“”å“©
  - RULE-SET,emby,â¤ï¸ Embyå…¬ç›Šæœ
  - RULE-SET,GameDownloadCN,ğŸ® æ¸¸æˆä¸­å›½
  - RULE-SET,LocalAreaNetwork,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,UnBan,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,SteamCN,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,China_Classical,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,ChinaIPs_Classical,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,Download,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,Proxy_Classical,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - RULE-SET,BanAD,ğŸ›‘ å¹¿å‘Šæ‹¦æˆª
  - RULE-SET,BanProgramAD,ğŸƒ åº”ç”¨å‡€åŒ–
  - GEOSITE,CN,ğŸ¯ å…¨çƒç›´è¿
  - GEOSITE,geolocation-!cn,ğŸ¯ å…¨çƒç›´è¿
  - GEOIP,CN,ğŸ¯ å…¨çƒç›´è¿
  - GEOIP,LAN,ğŸ¯ å…¨çƒç›´è¿
  - MATCH,ğŸŸ æ¼ç½‘ä¹‹é±¼
